---
- name: Configuracion automatica del nodo compute-0-3
  hosts: compute-0-3
  become: yes
  tasks:
    - name: 1. Instalar paquetes necesarios
      apt:
        name: [slurmd, munge, nfs-common, autofs, libnss-ldap, ldap-utils]
        state: present
        update_cache: yes

    - name: 2. Sincronizar configuracion LDAP
      copy:
        src: /etc/ldap.conf
        dest: /etc/ldap.conf

    - name: 3. Configurar nsswitch para reconocer usuarios LDAP
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^passwd:'
        line: 'passwd:         compat ldap'

    - name: 4. Copiar clave Munge (Seguridad de Slurm)
      copy:
        src: /etc/munge/munge.key
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0400'

    - name: 5. Configurar montaje automatico NFS (Autofs)
      copy:
        src: "{{ item }}"
        dest: "{{ item }}"
      with_items:
        - /etc/auto.master
        - /etc/auto.home

    - name: 6. Sincronizar configuracion de Slurm
      copy:
        src: /etc/slurm/slurm.conf
        dest: /etc/slurm/slurm.conf
        owner: slurm

    - name: 7. Asegurar que los servicios esten activos
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items: [munge, autofs, slurmd]
